services:
  backend:
    build: ./backend
    container_name: express_container
    restart: always
    mem_limit: 1g
    ports:
      - "7878:7878"
    environment:
      MONGO_URI: "your atlas string"

  frontend:
    build: ./frontend
    container_name: react_container
    restart: always
    mem_limit: 1g
    ports:
      - "5173:5173"
    depends_on:
      - backend
